
name:        smalltt
version:     0.2.0.0
license:     MIT
category:    Language
description: "Demo for high-performance elaboration with dependent types"
author:      "Andr치s Kov치cs"
maintainer:  "puttamalac@gmail.com"
copyright:   "2021 Andr치s Kov치cs"

flags:
  dump:
    description: dump core, stg and cmm to files
    default: false
    manual: true
  llvm:
    description: use llvm for codegen
    default: false
    manual: true
  debug:
    description: turn on debug info printing
    default: false
    manual: true

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - CPP
  - ConstraintKinds
  - DataKinds
  - DerivingVia
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - QualifiedDo
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - Strict
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-binds
  - -Wno-unused-matches
  - -Wno-missing-signatures
  - -Wno-unused-do-bind
  - -Wno-unticked-promoted-constructors
  - -fmax-worker-args=20
  - -O2

when:
  - condition: flag(dump)
    ghc-options:
      - -ddump-simpl
      - -ddump-stg
      - -ddump-cmm
      - -dsuppress-all
      - -dno-suppress-type-signatures
      - -ddump-to-file
  - condition: flag(llvm)
    ghc-options:
      - -fllvm
  - condition: flag(debug)
    cpp-options:
      - -DDEBUG

library:
  source-dirs:
    - src
  dependencies:
    - bytestring == 0.11.1.0
    - primdata
    - dynamic-array
    - flatparse
    - template-haskell
    - containers
    - time
    - ghc-prim

executables:
  smalltt-2-parseonly:
    source-dirs:
      - parseonly
    main:
      Main.hs
    ghc-options:
      - -rtsopts
      - -threaded
    dependencies:
      - smalltt
    when:
    - condition: false
      other-modules: Paths_smalltt

  smalltt-2-compact:
    source-dirs:
      - smalltt
    main:
      Main.hs
    ghc-options:
      - -rtsopts
      - -threaded
    dependencies:
      - bytestring
      - dynamic-array
      - flatparse
      - primdata
      - smalltt
    when:
    - condition: false
      other-modules: Paths_smalltt
