
name:        smalltt
version:     0.2.0.0
license:     MIT
category:    Language
description: "Demo for high-performance elaboration with dependent types"
author:      "Andr치s Kov치cs"
maintainer:  "puttamalac@gmail.com"
copyright:   "2021 Andr치s Kov치cs"

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingVia
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-binds
  - -Wno-unused-matches
  - -Wno-missing-signatures
  - -Wno-unused-do-bind
  - -Wno-unticked-promoted-constructors
  - -fmax-worker-args=12
  - -O2
  - -fllvm
  - -ddump-simpl
  - -ddump-to-file
  - -dsuppress-all
  - -dno-suppress-type-signatures
  - -ddump-stg

library:
  source-dirs:
    - src
  dependencies:
    - bytestring
    - primdata
    - dynamic-array
    - flatparse
    - template-haskell
    - containers

executables:
  smalltt-parseonly:
    source-dirs:
      - parseonly
    main:
      Main.hs
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-A1G
    dependencies:
      - smalltt
    when:
    - condition: false
      other-modules: Paths_smalltt

  smalltt:
    source-dirs:
      - smalltt
    main:
      Main.hs
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-A1G
    dependencies:
      - smalltt
    when:
    - condition: false
      other-modules: Paths_smalltt
