name:                smalltt
version:             0.2.0.0
github:              "AndrasKovacs/smalltt"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2018 Andr치s Kov치cs"

extra-source-files:
- README.md

synopsis:  Small type theory implementation
category:  Language
description: In README

dependencies:
- base >= 4.7 && < 5
default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- BangPatterns
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- EmptyCase
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- RankNTypes
- RoleAnnotations
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeInType
- UnboxedTuples
- UnicodeSyntax
- ViewPatterns

library:
  source-dirs:
      src
  dependencies:
    - dynamic-array
    - containers
    - ghc-prim
    - megaparsec
    - mtl
    - text
    - text-short
    - unordered-containers
  ghc-options:
    - -Wall
    - -Wno-missing-signatures
    - -Wno-name-shadowing
    - -Wno-unused-do-bind
    - -Wno-unused-matches
    - -Wno-partial-type-signatures
    - -O2
    # - -ddump-simpl -dsuppress-all -dno-suppress-type-signatures

executables:
  smalltt:
    main:  app/Main.hs
    ghc-options:
    - -rtsopts
    - -O2
    # - -ddump-simpl -dsuppress-all -dno-suppress-type-signatures
    dependencies:
    - smalltt
    - megaparsec
    - text
    - text-short
    - time
