
# resolver: lts-16.25
# resolver: lts-18.13
resolver: nightly-2022-07-07

packages:
- .

ghc-options:
  "$everything": -split-sections

extra-deps:
- git: https://github.com/AndrasKovacs/flatparse.git
  commit: f51ead69b568f73bb7d3b47f3bc7a2b2b6db259d
- git: https://github.com/AndrasKovacs/dynamic-array.git
  commit: c6eb41ea663c7a97c479e5536a8ef39ec848bcfa
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 4a7ed6b807a367a90c8dffaf1e98c3a0d0c28c32
