
resolver: lts-21.17

packages:
- .

ghc-options:
  "$everything": -split-sections

extra-deps:
- flatparse-0.5.0.1
- git: https://github.com/AndrasKovacs/dynamic-array.git
  commit: de37f8ba3b7186414aac5bd878f44b70b694890f
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 488d38201d0845a0e4e9e80ce78126ebae77350f
- git: https://github.com/AndrasKovacs/ghc-strict-implicit-params.git
  commit: 9097efc8860553f5d0189acc9bc56479c71c2125
