
# resolver: lts-16.25
# resolver: lts-18.13
resolver: nightly-2021-09-18

packages:
- .

ghc-options:
  "$everything": -split-sections

extra-deps:
- git: https://github.com/AndrasKovacs/flatparse.git
  commit: 8b532613e72911644f8ffe9afd05b1ac17f74cea
- git: https://github.com/AndrasKovacs/dynamic-array.git
  commit: c6eb41ea663c7a97c479e5536a8ef39ec848bcfa
- git: https://github.com/AndrasKovacs/primdata.git
  commit: d0234da40ffcd6aecd2fc817e5c4e07c42d4edc8
- bytestring-0.11.1.0
