
# resolver: lts-16.25
# resolver: lts-18.10
resolver: nightly-2021-09-18

packages:
- .

ghc-options:
  "$everything": -split-sections

extra-deps:
- git: https://github.com/AndrasKovacs/flatparse.git
  commit: 89a9d8ae65f1e450f55852cc2adb02ee6899f04c
- git: https://github.com/AndrasKovacs/dynamic-array.git
  commit: b5b0e9e4c737c7b72cc8d31232bc3d1fc36be0ad
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 44cac2350fb24dd57bdfa8cbee46b45c9332e50c
- bytestring-0.11.1.0
