
resolver: nightly-2023-02-09

packages:
- .

ghc-options:
  "$everything": -split-sections

extra-deps:
- git: https://github.com/AndrasKovacs/flatparse.git
  commit: eb98fcc0bff0c2aecd17a392b95ec2a87603736d
- git: https://github.com/AndrasKovacs/dynamic-array.git
  commit: a9880641ddc174db68c7e4735742e763d910453e
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 46b257c41a9eb0ad99ac1cd8c5dda029601089f5
- git: https://github.com/AndrasKovacs/ghc-strict-implicit-params.git
  commit: 215e0353374a61c0f8790371e4826b247c69580f
